{% set name = "pytest-run-parallel" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytest_run_parallel-{{ version }}.tar.gz
  sha256: 3b5ce6432ce435a4ccb65f8007290510a4fed2fc31f0b5b3474a7a69adca24c9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - pytest >=6.2.0

test:
  imports:
    - pytest_run_parallel
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/Quansight-Labs/pytest-run-parallel
  summary: A simple pytest plugin to run tests concurrently
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/Quansight-Labs/pytest-run-parallel

extra:
  recipe-maintainers:
    - lysnikolaou
    - andfoy
